kind: pipeline
type: docker
name: ci/cd
clone:
  disable: true
steps:
  - name: clone
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - mkdir $HOME/.ssh
      - echo -n "$SSH_KEY" > $HOME/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      - git clone $DRONE_GIT_SSH_URL .
      - git checkout $DRONE_COMMIT
  - name: build_docker
    image: plugins/docker
    pull: if-not-exists
    settings:
      registry: hub.oocc.es
      username:
        from_secret: nexus_docker_username
      password:
        from_secret: nexus_docker_password
      repo: hub.oocc.es/home/node-log
      tags: ${DRONE_COMMIT=latest}${DRONE_BUILD_NUMBER}
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: k8s_host
      username:
        from_secret: k8s_username
      password:
        from_secret: k8s_password
      port: 22
      command_timeout: 2m
      script:
        - echo ${DRONE_COMMIT}${DRONE_BUILD_NUMBER}
        - kubectl apply -f https://git.oocc.es/oocc/k3s/raw/branch/master/node-log.yaml
        - kubectl set image deployment/blog blog=hub.oocc.es/home/node-log:${DRONE_COMMIT}${DRONE_BUILD_NUMBER}
trigger:
  event:
    exclude:
      - promote
