kind: pipeline
type: docker
name: ci/cd
clone:
  disable: true
steps:
  - name: clone
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - mkdir $HOME/.ssh
      - echo -n "$SSH_KEY" > $HOME/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa

      - touch /root/.ssh/known_hosts
      - chmod 600 /root/.ssh/known_hosts
      - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null

      - git clone $DRONE_GIT_SSH_URL .
      - git checkout $DRONE_COMMIT
  - name: build_docker
    image: plugins/docker
    pull: if-not-exists
    settings:
      registry: hub.oocc.es
      username:
        from_secret: nexus_docker_username
      password:
        from_secret: nexus_docker_password
      repo: hub.oocc.es/home/node-log
      tags: latest
#  - name: deploy
#    image: appleboy/drone-scp
#    depends_on:
#      - clone
#    settings:
#      host:
#        from_secret: server_host
#      port: 22
#      username:
#        from_secret: username
#      password:
#        from_secret: server_password
#      overwrite: true
#      target: /root/node-log
#      source:
#        - app.js
#        - es.js
#        - config.js
#        - package.json
#        - pnpm-lock.yaml
#        - zzf.gif
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: k8s_host
      username:
        from_secret: k8s_username
      password:
        from_secret: k8s_password
      port: 22
      command_timeout: 2m
      script:
        - kubectl scale --replicas=0 -f https://git.oocc.es/oocc/k3s/raw/branch/master/node-log.yaml
        - kubectl apply -f https://git.oocc.es/oocc/k3s/raw/branch/master/node-log.yaml
trigger:
  event:
    exclude:
      - promote
